# Stage 1: Build the frontend
FROM node:20.17-slim AS build-frontend

WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the source code
COPY . .

# Build the frontend for production
RUN npm run build

# Stage 2: Serve the frontend
FROM nginx:alpine

COPY --from=build-frontend /usr/src/app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
