# Use Node.js image as base for backend tests
FROM node:20.17-slim

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json
COPY package*.json ./

RUN npm i -g npm@latest; \
 # Install pnpm
 npm install -g pnpm; \
 pnpm --version; \
 pnpm setup; \
 mkdir -p /usr/local/share/pnpm &&\
 export PNPM_HOME="/usr/local/share/pnpm" &&\
 export PATH="$PNPM_HOME:$PATH"; \
 pnpm bin -g&&\
# Install dependencies
 pnpm install

# Copy the entire backend source code
COPY . .

# Build the NestJS app
RUN pnpm run build

# Run the tests
CMD ["pnpm", "run", "test"]
